name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26
  - scipy=1.15
  - matplotlib=3.10
  - h5py=3.13
  - ipykernel=6.29
  - notebook=7.4
  - jupyterlab=4.4
  - decorator=5.1
  - pip